### ISSUE TITLE
KongStartupExtensions/UseKongHealthChecks中不应该使用Console.WriteLine

### ISSUE THREAD

**Issue by gavinfang-fi** [lianggx/Kong.Net#1]
Console.WriteLine可能会带来一些性能上的影响, 下面是一个Rick Strahl的帖子:
https://weblog.west-wind.com/posts/2018/Dec/31/Dont-let-ASPNET-Core-Default-Console-Logging-Slow-your-App-down

**Comment by Rwing** [comment]
大量的打印至控制台会影响性能，这极少量的没关系的。
